name: Builder

on:
  push:
    tags: '*'
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: build
      run: |
        ./gradlew
