name: Builder

on:
  push:
    tags: '*'
  workflow_dispatch:
  
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: fool the tool
      run: |
        cd /usr/local/lib/android/sdk/ndk-bundle/toolchains
        ls -lah .
        ln -s aarch64-linux-android-4.9 mips64el-linux-android
        ln -s arm-linux-androideabi-4.9 mipsel-linux-android
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: build
      run: |
        chmod +x ./gradlew
        ./gradlew build
